apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iq.name" . }}
  labels:
    {{- include "iq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "iq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "iq.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "iq.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: {path: {{ .Values.probes.path }}, port: {{ .Values.probes.port }}}
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: {path: {{ .Values.probes.path }}, port: {{ .Values.probes.port }}}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
