apiVersion: v1
kind: Service
metadata:
  name: {{ include "iq.name" . }}
  labels:
    {{- include "iq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "iq.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
